# Japanese translations for PROJECT.
# Copyright (C) 2025 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2025-05-20 11:58+0900\n"
"PO-Revision-Date: 2025-04-09 00:48+0900\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: ja\n"
"Language-Team: ja <LL@li.org>\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: pyfemtet/core.py:9
msgid "Starting from version 1.0, the import method for the Error classes has changed. Please change imports such as `from pyfemtet.core import ModelError` to `from pyfemtet.opt.exceptions import ModelError`. For more details, please see https://pyfemtet.readthedocs.io/en/stable/pages/migration_to_v1.html."
msgstr "バージョン1.0以降、Errorクラスのインポート方法が変更されました。`from pyfemtet.core import ModelError` のようなインポートを `from pyfemtet.opt.exceptions import ModelError` に変更してください。詳細については https://pyfemtet.readthedocs.io/en/stable/pages/migration_to_v1.html をご参照ください。"

#: pyfemtet/_i18n/messages.py:6
msgid "Hello!"
msgstr "こんにちは！"

#: pyfemtet/_i18n/messages.py:9
msgid "Press enter to quit..."
msgstr "終了するには Enter キーを押してください..."

#: pyfemtet/_i18n/messages.py:10
msgid "constraint"
msgstr "拘束"

#: pyfemtet/_i18n/messages.py:11
msgid "hidden constraint"
msgstr "隠れた拘束"

#: pyfemtet/_i18n/messages.py:14
msgid "Waiting for launch femtet..."
msgstr "femtet の起動待ち..."

#: pyfemtet/_i18n/messages.py:15
msgid "Trying to connect Femtet..."
msgstr "Femtet に接続中..."

#: pyfemtet/_i18n/messages.py:20
#, python-brace-format
msgid "Successfully connected. The pid of Femtet is {pid}."
msgstr "正常に接続されました。FemtetのPIDは{pid}です。"

#: pyfemtet/_i18n/messages.py:27
#, python-brace-format
msgid "Searching Femtet (pid = {pid}) ..."
msgstr "Femtet (pid = {pid}) を探しています・・・"

#: pyfemtet/_i18n/messages.py:34
#, python-brace-format
msgid "Connection to Femtet (pid = {pid}) was notestablished in {timeout} sec"
msgstr "Femtet への接続(pid = {pid})は{timeout}秒以内に確立されませんでした"

#: pyfemtet/_i18n/messages.py:41
msgid "The magnitude relationship is incorrect."
msgstr "大きさの関係が正しくありません。"

#: pyfemtet/_i18n/messages.py:42
msgid "The direction of the objective function must be 'minimize', 'maximize' or a number. "
msgstr "目的関数の方向は「minimize」か「maximize」、または数値で指定してください。"

#: pyfemtet/_i18n/messages.py:43
msgid "The variable name, object name, or constraint name contains characters that cannot be encoded. Do not use environment-dependent characters."
msgstr "変数名、オブジェクト名、または拘束名にエンコードできない文字が含まれています。環境依存の文字は使用しないでください。"

#: pyfemtet/_i18n/messages.py:44
msgid "The running configuration does not match the configuration in the csv file."
msgstr "現在の設定はcsvファイルの設定と一致していません。"

#: pyfemtet/_i18n/messages.py:47
msgid "Please specify initial_value."
msgstr "initial_value を指定してください。"

#: pyfemtet/_i18n/messages.py:49
msgid "Constraint functions are evaluated before analysis is performed, so do not access Femtet.Gogh. If you want your constraints to include values after analysis is performed, set the `strict` argument to False."
msgstr "拘束関数は解析を実行する前に評価されるため、Femtet.Gogh にアクセスしないでください。解析実行後の値を拘束に含めたい場合は、`strict` 引数を False に設定してください。"

#: pyfemtet/_i18n/messages.py:54
msgid "Optimization finished. Results were saved in following:"
msgstr "最適化が終了しました。結果は以下に保存されました："

#: pyfemtet/_i18n/messages.py:55
msgid "No bounds specified."
msgstr "境界条件が指定されていません。"

#: pyfemtet/_i18n/messages.py:56 pyfemtet/opt/femopt.py:426
msgid "The optimization is now complete. You can view the results on the monitor until you press Enter to exit the program."
msgstr "最適化が完了しました。Enterキーを押してプログラムを終了するまで、モニターで結果を確認できます。"

#: pyfemtet/_i18n/messages.py:59
msgid "\"%UGII_BASE_DIR%\\NXBIN\\run_journal.exe\" is not found. Make sure you have NX installed and the environment variable UGII_BASE_DIR is set."
msgstr "\"%UGII_BASE_DIR%\\NXBIN\\run_journal.exe\" が見つかりません。NX がインストールされており、環境変数 UGII_BASE_DIR が設定されていることを確認してください。"

#: pyfemtet/_i18n/messages.py:60
msgid "Model reconstruction failed."
msgstr "モデル再構築に失敗しました。"

#: pyfemtet/_i18n/messages.py:61
msgid "Model update failed."
msgstr "モデルの更新に失敗しました。"

#: pyfemtet/_i18n/messages.py:62
#: pyfemtet/opt/interface/_femtet_interface/femtet_interface.py:358
msgid "It was detected that the configuration of Femtet python macro constants has not been completed. The configuration was done automatically (python -m win32com.client.makepy FemtetMacro). Please restart the program. If the error persists, please run \"py -m win32com.client.makepy FemtetMacro\" or \"python -m win32com.client.makepy FemtetMacro\" on the command prompt."
msgstr "Femtet の python マクロ定数の設定が完了していないことが検出されました。設定は自動的に行われました(python -m win32com.client.makepy FemtetMacro)。プログラムを再起動してください。エラーが続く場合は、コマンドプロンプトで「py -m win32com.client.makepy FemtetMacro」または「python -m win32com.client.makepy FemtetMacro」を実行してください。"

#: pyfemtet/_i18n/messages.py:63
#: pyfemtet/opt/interface/_femtet_interface/femtet_interface.py:385
msgid "Failed to connect to Femtet."
msgstr "Femtet への接続に失敗しました。"

#: pyfemtet/_i18n/messages.py:68
#, python-brace-format
msgid "The Femtet process crashed and Python failed to restore Femtet. API: {name}"
msgstr "Femtet プロセスがクラッシュし、Python が Femtet を復元できませんでした。API: {name}"

#: pyfemtet/_i18n/messages.py:77
#, python-brace-format
msgid "An abnormal termination of the Femtet process has been detected. Recovery will be attempted. API: {name}"
msgstr "Femtetプロセスの異常終了が検出されました。リカバリを試みます。API: {name}"

#: pyfemtet/_i18n/messages.py:83
msgid "Femtet has been restarted and will perform analysis and attempt to recover."
msgstr "Femtetが再起動され、解析を実行して復旧を試みます。"

#: pyfemtet/_i18n/messages.py:84
msgid "If you specify 'new' as the 'connect_method' argument, set the 'femprj_path' argument to existing femprj file path."
msgstr "'connect_method' 引数に 'new' を指定する場合は、'femprj_path' 引数に既存の femprj ファイルのパスを設定してください。"

#: pyfemtet/_i18n/messages.py:85
msgid "The specified variable is not included in the Femtet analysis model. Note the capitalization of the variable."
msgstr "指定された変数はFemtet解析モデルに含まれていません。変数の大文字・小文字に注意してください。"

#: pyfemtet/_i18n/messages.py:86
msgid "The following APIs are not accessible: "
msgstr "以下のAPIにはアクセスできません:"

#: pyfemtet/_i18n/messages.py:87
msgid "Macros may not be enabled in the installed version of Femtet. Please run the \"Enable Macros\" command from the start menu with administrator privileges in the same version of Femtet that is installed."
msgstr "インストールされている Femtet のバージョンではマクロが有効になっていない可能性があります。インストールされている同じバージョンの Femtet を管理者権限で起動し、スタートメニューから「Enable Macros」コマンドを実行してください。"

#: pyfemtet/_i18n/messages.py:88
msgid "No analysis model is open"
msgstr "解析モデルが開かれていません"

#: pyfemtet/_i18n/messages.py:89
msgid "The analysis model does not contain any variables."
msgstr "解析モデルに変数が含まれていません。"

#: pyfemtet/_i18n/messages.py:90
msgid "Failed to update variables:"
msgstr "変数の更新に失敗しました："

#: pyfemtet/_i18n/messages.py:91
msgid "The specified variable is not included in the analysis model and will be ignored."
msgstr "指定された変数は解析モデルに含まれておらず、無視されます。"

#: pyfemtet/_i18n/messages.py:92
msgid "Model history re-execute failed."
msgstr "モデル履歴の再実行に失敗しました。"

#: pyfemtet/_i18n/messages.py:93
msgid "Model redraw failed."
msgstr "モデルの再描画に失敗しました。"

#: pyfemtet/_i18n/messages.py:94
msgid "Mesh generation failed"
msgstr "メッシュ生成に失敗しました"

#: pyfemtet/_i18n/messages.py:95
msgid "Parametric solve failed"
msgstr "パラメトリック解析に失敗しました"

#: pyfemtet/_i18n/messages.py:96
msgid "Solve failed."
msgstr "解析に失敗しました。"

#: pyfemtet/_i18n/messages.py:97
msgid "Failed to open result."
msgstr "結果を開くことに失敗しました。"

#: pyfemtet/_i18n/messages.py:98
#: pyfemtet/opt/interface/_femtet_interface/femtet_interface.py:241
msgid "Failed to close Femtet."
msgstr "Femtet を終了できませんでした。"

#: pyfemtet/_i18n/messages.py:99
msgid "Failed to save result (.pdt) file."
msgstr "結果ファイル(.pdt)の保存に失敗しました。"

#: pyfemtet/_i18n/messages.py:100
msgid "Failed to save screenshot (.jpg)."
msgstr "スクリーンショット(.jpg)の保存に失敗しました。"

#: pyfemtet/_i18n/messages.py:101
msgid "Screenshot (.jpg) is not found."
msgstr "スクリーンショット(.jpg)が見つかりません。"

#: pyfemtet/_i18n/messages.py:102
msgid "Failed to update model in solidworks."
msgstr "SolidWorks でモデルの更新に失敗しました。"

#: pyfemtet/_i18n/messages.py:103
msgid "Probability of feasibility is less than threshold."
msgstr "実行可能性の確率がしきい値未満です。"

#: pyfemtet/_i18n/messages.py:104
#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:936
msgid "Terminating Excel process..."
msgstr "Excel プロセスを終了しています..."

#: pyfemtet/_i18n/messages.py:105
#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:955
msgid "Excel process is terminated."
msgstr "Excel のプロセスが終了しました。"

#: pyfemtet/_i18n/messages.py:106
#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:961
msgid "Restore Femtet setting of autosave."
msgstr "autosave の Femtet 設定を復元します。"

#: pyfemtet/_i18n/messages.py:107
msgid "Failed to make output from Femtet. Please check output settings of Parametric Analysis."
msgstr "Femtetからの出力の作成に失敗しました。パラメトリック解析の出力設定を確認してください。"

#: pyfemtet/_i18n/messages.py:111
msgid "The following features are not supported by the specified optimization method. "
msgstr "指定された最適化手法では、次の機能はサポートされていません。"

#: pyfemtet/_i18n/messages.py:112
msgid "The parameter set does not match the one added with add_init_parameter."
msgstr "パラメータセットがadd_init_parameterで追加されたものと一致しません。"

#: pyfemtet/_i18n/messages.py:113
msgid "An exception has occurred during FEM update. Current parameters are: "
msgstr "FEM 更新中に例外が発生しました。現在のパラメータは："

#: pyfemtet/_i18n/messages.py:114
msgid "The constraints were not satisfied for the following sets of variables:"
msgstr "以下の変数セットで拘束が満たされませんでした:"

#: pyfemtet/_i18n/messages.py:115
msgid "Current parameter set cannot update FEM and this optimization method cannot skip current parameter set. The optimization process will be terminated."
msgstr "現在のパラメータセットでは FEM を更新できません。また、この最適化手法は現在のパラメータセットをスキップできません。最適化処理を終了します。"

#: pyfemtet/_i18n/messages.py:116
msgid "Optimization has been interrupted. Note that you cannot acquire the OptimizationResult in case of `trust-constr`, `TNC`, `SLSQP` or `COBYLA`."
msgstr "最適化は中断されました。`trust-constr`、`TNC`、`SLSQP`、または`COBYLA`の場合、OptimizationResultを取得できないことに注意してください。"

#: pyfemtet/_i18n/messages.py:117
msgid "You can use parameter constraint only with BoTorchSampler."
msgstr "パラメータ拘束はBoTorchSamplerでのみ使用できます。"

#: pyfemtet/_i18n/messages.py:118
msgid "Scipy is deterministic, so whether you set a seed or not will not change the results."
msgstr "Scipyは決定論的であるため、シードを設定してもしなくても結果は変わりません。"

#: pyfemtet/_i18n/messages.py:119
msgid "Start to candidate new parameter set with constraints. This process may take a long time."
msgstr "拘束付きの新しいパラメータセットの候補作成を開始します。この処理には時間がかかることがあります。"

#: pyfemtet/_i18n/messages.py:120
msgid "Updating FEM parameter during evaluating constraints take a long time. Please consider not to use FEM variables in constraint functions and set `update_fem` to False."
msgstr "拘束評価中の FEM パラメータの更新には時間がかかります。拘束関数で FEM 変数を使用せず、`update_fem` を False に設定することを検討してください。"

#: pyfemtet/_i18n/messages.py:126
#: pyfemtet/opt/optimizer/optuna_optimizer/_optuna_optimizer.py:470
#, python-brace-format
msgid "The given argument {key} is not included in ones of {sampler_name}. {key} is ignored."
msgstr "指定された引数 {key} は {sampler_name} のいずれにも含まれていません。{key} は無視されます。"

#: pyfemtet/_i18n/messages.py:134
msgid "Sometimes Nelder-Mead cannot start optimization with the initial condition what is same with lower bounds or upper bounds."
msgstr "初期条件が下限または上限と同じ場合、Nelder-Mead は最適化を開始できないことがあります。"

#: pyfemtet/_i18n/messages.py:139
msgid "Cannot use categorical parameter with ScipyOptimizer"
msgstr "ScipyOptimizer でカテゴリパラメータは使用できません"

#: pyfemtet/_i18n/messages.py:142
msgid ""
"Hard constraint violation! scipy cannot continue optimization. Only `SLSQP` supports optimization with hard constraint optimization problem. If you see this message even if you are using it, please try to following:\n"
"- Use small `eps` by `options` argument.\n"
"- Set `constraint_enhancement`to the value that it larger than the variation of the constraint function when input variables within the range of `eps`."
msgstr ""

#: pyfemtet/_i18n/messages.py:162
msgid "ScipyOptimizer cannot continue optimization when encountered the input variables that break FEM model."
msgstr "ScipyOptimizer は FEM モデルを破損する入力変数に遭遇した場合、最適化を継続できません。"

#: pyfemtet/_i18n/messages.py:168
msgid "ScipyOptimizer cannot skip solve."
msgstr "ScipyOptimizer は解析をスキップできません。"

#: pyfemtet/_i18n/messages.py:172
#, python-brace-format
msgid "{method} cannot handle hard constraint."
msgstr "{method} はハード拘束を扱うことができません。"

#: pyfemtet/_i18n/messages.py:175
msgid "SLSQP cannot handle soft constraint. The constraint is handled as a hard one."
msgstr "SLSQPはソフト拘束を扱えません。拘束はハード拘束として扱われます。"

#: pyfemtet/_i18n/messages.py:181
#: pyfemtet/opt/optimizer/optuna_optimizer/_pof_botorch/enable_nonlinear_constraint.py:72
msgid "Accessing FEM API inside hard constraint function may be very slow."
msgstr "ハード拘束関数内で FEM API にアクセスすると非常に遅くなる可能性があります。"

#: pyfemtet/_i18n/messages.py:184
#: pyfemtet/opt/optimizer/optuna_optimizer/_pof_botorch/enable_nonlinear_constraint.py:211
msgid "gen_batch_initial_conditions() failed to generate feasible initial conditions for acquisition function optimization sub-problem, so trying to use random feasible parameters as initial conditions.The constraint functions or solutions spaces may be too complicated."
msgstr "gen_batch_initial_conditions() は取得関数最適化のサブ問題の実行可能な初期条件を生成できなかったため、ランダムな実行可能パラメータを初期条件として使用しようとしています。拘束関数または解空間が複雑すぎる可能性があります。"

#: pyfemtet/_i18n/messages.py:195
msgid "Connect to Femtet"
msgstr "Femtet に接続"

#: pyfemtet/_i18n/messages.py:196
msgid "Analysis model name described in csv does not exist in project."
msgstr "csv に記載されている解析モデル名がプロジェクト内に存在しません。"

#: pyfemtet/_i18n/messages.py:197
msgid "History csv is not read yet. Open your project manually."
msgstr "履歴 csv はまだ読み込まれていません。プロジェクトを手動で開いてください。"

#: pyfemtet/_i18n/messages.py:198
msgid "Cannot read project data from csv. Open your project manually."
msgstr "csvからプロジェクトデータを読み取れません。プロジェクトを手動で開いてください。"

#: pyfemtet/_i18n/messages.py:199
msgid ".femprj file described in csv is not found. Open your project manually."
msgstr "csvで記述された.femprjファイルが見つかりません。プロジェクトを手動で開いてください。"

#: pyfemtet/_i18n/messages.py:200
msgid "Analysis model name is not specified. Open your model in the project manually."
msgstr "解析モデル名が指定されていません。プロジェクト内でモデルを手動で開いてください。"

#: pyfemtet/_i18n/messages.py:202
msgid "Constraint"
msgstr "拘束"

#: pyfemtet/_i18n/messages.py:203
msgid "feasible"
msgstr "実行可能"

#: pyfemtet/_i18n/messages.py:204
msgid "infeasible"
msgstr "実行不可能"

#: pyfemtet/_i18n/messages.py:205
msgid "Optimality"
msgstr "最適性"

#: pyfemtet/_i18n/messages.py:206
msgid "non dominated"
msgstr "非劣解"

#: pyfemtet/_i18n/messages.py:207
msgid "dominated"
msgstr "劣解"

#: pyfemtet/_i18n/messages.py:208
msgid "Hypervolume Plot"
msgstr "ハイパーボリュームプロット"

#: pyfemtet/_i18n/messages.py:209
msgid "Objective Plot"
msgstr "目的関数プロット"

#: pyfemtet/_i18n/messages.py:210
msgid "Multi Objective Pair Plot"
msgstr "多目的ペアプロット"

#: pyfemtet/_i18n/messages.py:211
msgid "Succeeded trial number"
msgstr "成功した試行回数"

#: pyfemtet/_i18n/messages.py:212
msgid "All solutions"
msgstr "すべての解"

#: pyfemtet/_i18n/messages.py:213
msgid "Transition of<br>optimal solutions"
msgstr "最適解の推移"

#: pyfemtet/_i18n/messages.py:214
msgid "Target value"
msgstr "目標値"

#: pyfemtet/_i18n/messages.py:216
msgid "Objectives"
msgstr "目的"

#: pyfemtet/_i18n/messages.py:217
msgid "Objectives (all)"
msgstr "目的(すべて)"

#: pyfemtet/_i18n/messages.py:219
#: pyfemtet/opt/visualization/plotter/pm_graph_creator.py:343
#: pyfemtet/opt/visualization/plotter/pm_graph_creator.py:350
msgid "Prediction Model"
msgstr "予測モデル"

#: pyfemtet/_i18n/messages.py:220
msgid " Recalculate Model"
msgstr "モデルを再計算する"

#: pyfemtet/_i18n/messages.py:221
msgid " Redraw graph"
msgstr "グラフを再描画"

#: pyfemtet/_i18n/messages.py:222
msgid "Parameter"
msgstr "パラメータ"

#: pyfemtet/_i18n/messages.py:223
msgid "Parameter2"
msgstr "パラメータ2"

#: pyfemtet/_i18n/messages.py:224
msgid "Objective"
msgstr "目的"

#: pyfemtet/_i18n/messages.py:225
msgid "No history selected."
msgstr "履歴が選択されていません。"

#: pyfemtet/_i18n/messages.py:226
msgid "No FEM result (yet)."
msgstr "FEM 結果なし(未解析)。"

#: pyfemtet/_i18n/messages.py:227
msgid "Prediction model is not calculated yet."
msgstr "予測モデルはまだ計算されていません。"

#: pyfemtet/_i18n/messages.py:228
msgid "Cannot select same parameter"
msgstr "同じパラメータを選択することはできません"

#: pyfemtet/_i18n/messages.py:229
msgid "3D graph (two or more parameters required)"
msgstr "3D グラフ(2つ以上のパラメータが必要)"

#: pyfemtet/_i18n/messages.py:231
msgid "Prediction Model of Objective"
msgstr "目的関数の予測モデル"

#: pyfemtet/_i18n/messages.py:232
msgid "prediction model"
msgstr "予測モデル"

#: pyfemtet/_i18n/messages.py:233
msgid "std. dev. of model"
msgstr "モデルの標準偏差"

#: pyfemtet/_i18n/messages.py:235
msgid "Progress"
msgstr "進捗"

#: pyfemtet/_i18n/messages.py:236
#: pyfemtet/opt/visualization/plotter/pm_graph_creator.py:168
#: pyfemtet/opt/visualization/plotter/pm_graph_creator.py:193
msgid "Prediction"
msgstr "予測"

#: pyfemtet/_i18n/messages.py:237
msgid "Workers"
msgstr "並列プロセス"

#: pyfemtet/_i18n/messages.py:238
msgid "Details"
msgstr "詳細"

#: pyfemtet/_i18n/messages.py:240
msgid "Optimization status will be shown here."
msgstr "最適化状況がここに表示されます。"

#: pyfemtet/_i18n/messages.py:241
msgid "Auto-update graph"
msgstr "グラフを自動更新"

#: pyfemtet/_i18n/messages.py:242
msgid "Interrupt Optimization"
msgstr "最適化を中断"

#: pyfemtet/_i18n/messages.py:244
msgid "Result"
msgstr "結果"

#: pyfemtet/_i18n/messages.py:246
msgid "Open Result in Femtet"
msgstr "Femtetで結果を開く"

#: pyfemtet/_i18n/messages.py:247
msgid "Reconstruct Model"
msgstr "モデルを再構築"

#: pyfemtet/_i18n/messages.py:248
msgid "Drag and drop or select csv file"
msgstr "ドラッグアンドドロップまたはcsvファイルを選択してください"

#: pyfemtet/_i18n/messages.py:249
msgid "Connection to Femtet is not established. Launch Femtet and Open a project."
msgstr "Femtet への接続が確立されていません。Femtet を起動してプロジェクトを開いてください。"

#: pyfemtet/_i18n/messages.py:250
msgid "No result plot is selected."
msgstr "結果プロットが選択されていません。"

#: pyfemtet/_i18n/messages.py:251
msgid "The femprj file path in the history csv is not found or valid."
msgstr "ヒストリ CSV 内の femprj ファイルパスが見つからないか有効ではありません。"

#: pyfemtet/_i18n/messages.py:252
msgid "The model name in the history csv is not found."
msgstr "履歴CSV内のモデル名が見つかりません。"

#: pyfemtet/_i18n/messages.py:253
msgid ".pdt file is not found. Please check the .Results folder. Note that .pdt file save mode depends on the `save_pdt` argument of FemtetInterface in optimization script(default to `all`)."
msgstr ".pdt ファイルが見つかりません。.Results フォルダを確認してください。.pdt ファイルの保存モードは、最適化スクリプト内の FemtetInterface の `save_pdt` 引数に依存します(デフォルトは `all` です)。"

#: pyfemtet/_i18n/messages.py:258
msgid "Failed to open "
msgstr "次のファイルを開けませんでした: "

#: pyfemtet/_i18n/messages.py:259
msgid "Specified model is not in current project. Please check opened project. For example, not \"analysis model only\" but your .femprj file."
msgstr "指定されたモデルは現在のプロジェクトに含まれていません。開いているプロジェクトを確認してください。例えば「解析結果単体」を開いている場合、プロジェクトを .femprj に切り替えてください。"

#: pyfemtet/_i18n/messages.py:262
msgid ".femprj file path of the history csv is invalid. Please certify matching between csv and opening .femprj file."
msgstr "履歴csvの.femprjファイルパスが無効です。csvと開いている.femprjファイルの一致を確認してください。"

#: pyfemtet/_i18n/messages.py:263
msgid "Analysis model name of the history csv is invalid. Please certify matching between csv and opening analysis model."
msgstr "履歴csvの解析モデル名が無効です。csvと開いている解析モデルの一致を確認してください。"

#: pyfemtet/_i18n/messages.py:264
msgid "Analysis model name of the history csv and opened in Femtet is inconsistent. Please certify matching between csv and opening analysis model."
msgstr "履歴csvの解析モデル名とFEMTETで開いているモデル名が一致していません。csvと開いている解析モデルの一致を確認してください。"

#: pyfemtet/_i18n/messages.py:265
msgid "tutorial mode"
msgstr "チュートリアルモード"

#: pyfemtet/_i18n/messages.py:266
msgid "Load Sample CSV"
msgstr "サンプル CSV を読み込み"

#: pyfemtet/_i18n/messages.py:267
msgid "Load CSV"
msgstr "CSVを読み込み"

#: pyfemtet/_i18n/messages.py:268
msgid "Open your optimization result. Then connecting to femtet will start automatically. Note that in tutorial mode, this button loads the ready-made sample csv and open sample femprj."
msgstr "最適化結果を開いてください。すると自動的に femtet への接続が開始されます。なお、チュートリアルモードでは、このボタンを押すと既成のサンプル csv を読み込み、サンプル femprj を開きます。"

#: pyfemtet/_i18n/messages.py:270
msgid "Main Graph"
msgstr "メイングラフ"

#: pyfemtet/_i18n/messages.py:271
msgid "Here the optimization history is shown. Each plot represents single FEM result. You can pick a result to open the corresponding result in Femtet. "
msgstr "ここに最適化履歴が表示されます。各プロットは単一のFEM結果を表しています。結果を選択すると、対応する結果をFemtetで開くことができます。"

#: pyfemtet/_i18n/messages.py:274
msgid "Open Result"
msgstr "結果を開く"

#: pyfemtet/_i18n/messages.py:275
msgid "After pick a point in the main graph, This button shows the corresponding FEM result in Femtet."
msgstr "メイングラフで点を選択した後、このボタンは対応するFEM結果をFemtetに表示します。"

#: pyfemtet/_i18n/messages.py:277
msgid "Re-connect to Femtet."
msgstr "Femtet に(再)接続します。"

#: pyfemtet/_i18n/messages.py:278
msgid "Sample csv is not found. Please consider to re-install pyfemtet by `py -m pip install pyfemtet -U --force-reinstall`"
msgstr "サンプル csv が見つかりません。`py -m pip install pyfemtet -U --force-reinstall` コマンドで pyfemtet の再インストールを検討してください。"

#: pyfemtet/_i18n/messages.py:279
msgid "Sample femprj file is not found. Please consider to re-install pyfemtet by `py -m pip install pyfemtet -U --force-reinstall`"
msgstr "サンプル femprj ファイルが見つかりません。`py -m pip install pyfemtet -U --force-reinstall` を実行して pyfemtet を再インストールしてください。"

#: pyfemtet/_i18n/messages.py:280
msgid "Sample femprj result folder is not found. Please consider to re-install pyfemtet by `py -m pip install pyfemtet -U --force-reinstall`"
msgstr "サンプル femprj 結果フォルダが見つかりません。`py -m pip install pyfemtet -U --force-reinstall` で pyfemtet を再インストールしてください。"

#: pyfemtet/_i18n/messages.py:282
msgid "Loading data..."
msgstr "データを読み込み中..."

#: pyfemtet/_i18n/messages.py:283
msgid "Plots of objectives versus trials"
msgstr "目的関数値と試行回数のプロット"

#: pyfemtet/_i18n/messages.py:284
msgid "The vertical axis is the objective, and the horizontal axis is the number of trials."
msgstr "縦軸は目的関数、横軸は試行回数です。"

#: pyfemtet/_i18n/messages.py:285
msgid "Parallel coordinate plots"
msgstr "並行座標プロット"

#: pyfemtet/_i18n/messages.py:286
msgid "The vertical axis is an objective or parameters, and one polyline indicates one result."
msgstr "縦軸は目的関数またはパラメータを表しており、一本の折れ線が一つの結果を示します。"

#: pyfemtet/_i18n/messages.py:287
msgid "The heatmap of objectives"
msgstr "目的のヒートマップ"

#: pyfemtet/_i18n/messages.py:288
msgid "The axes are parameters, and the color shows objective value."
msgstr "軸はパラメータで、色は目的関数の値を示します。"

#: pyfemtet/_i18n/messages.py:289
msgid "The response of an objective versus one parameter"
msgstr "1つのパラメータに対する目的関数の応答"

#: pyfemtet/_i18n/messages.py:290
msgid "The vertical axis is objective, and the horizontal axis is parameter."
msgstr "縦軸は目的関数、横軸はパラメータです。"

#: pyfemtet/_i18n/messages.py:291
msgid "The importance of parameters evaluated by fANOVA"
msgstr "fANOVA によって評価されたパラメータの重要性"

#: pyfemtet/_i18n/messages.py:292
msgid "The normalized relative importance of parameters. Please note that the importance is calculated from the overall relationship of the input-output response, rather than from a specific solution."
msgstr "パラメータの正規化された相対重要度です。重要度は特定の解析結果からではなく、入力と出力の全体的な関係性から算出されていることにご注意ください。"

#: pyfemtet/_util/femtet_exit.py:48
#, python-brace-format
msgid "Femtet.Exit() does not finished in {timeout} sec. Most common reason is that a dialog is opening in Femtet and waiting user input. Please close the dialog if it exists."
msgstr "Femtet.Exit() は {timeout} 秒以内に終了しませんでした。最も一般的な原因は、Femtet 内でダイアログが開かれており、ユーザーの入力を待っていることです。ダイアログが存在する場合は閉じてください。"

#: pyfemtet/_util/femtet_exit.py:70
msgid "Macro version is not consistent to the one of Femtet.exe. Please consider toexecute ``Enable Macros`` of current Femtet version to fix it."
msgstr "マクロのバージョンがFemtet.exeのものと一致していません。修正するために、現在のFemtetバージョンで「Enable Macros」を実行してください。"

#: pyfemtet/_util/femtet_exit.py:91
msgid "Failed to close Femtet in 30 seconds."
msgstr "30秒以内にFemtetの終了に失敗しました。"

#: pyfemtet/_util/helper.py:48
#, python-brace-format
msgid "{name} does not finished in {timeout} seconds."
msgstr "{name} は {timeout} 秒以内に終了しませんでした。"

#: pyfemtet/opt/femopt.py:194
#, python-brace-format
msgid "===== pyfemtet version {ver} ====="
msgstr "===== pyfemtet バージョン {ver} ====="

#: pyfemtet/opt/femopt.py:216
msgid "Launching processes..."
msgstr "プロセスを起動しています..."

#: pyfemtet/opt/femopt.py:223
msgid "Connecting cluster..."
msgstr "クラスタに接続中..."

#: pyfemtet/opt/femopt.py:234
msgid "Launching threads..."
msgstr "スレッドを起動しています..."

#: pyfemtet/opt/femopt.py:248
msgid "Setting up..."
msgstr "設定中..."

#: pyfemtet/opt/femopt.py:277
msgid "Launching Monitor..."
msgstr "モニターを起動しています..."

#: pyfemtet/opt/femopt.py:298
msgid "Setting up optimization problem..."
msgstr "最適化問題を設定中..."

#: pyfemtet/opt/femopt.py:347
#, python-brace-format
msgid "Cannot save history. The most common reason is that the csv is opened by another program (such as Excel). Please free {path} or lost the optimization history."
msgstr "履歴を保存できません。最も一般的な原因は、csvファイルが他のプログラム(例えばExcel)によって開かれていることです。{path}の使用を解除するか、最適化履歴が失われます。"

#: pyfemtet/opt/femopt.py:381
msgid "Getting monitor host information is failed within 30 seconds. It can not be able to terminate by requesting POST `<host>:<port>/interrupt` by an external process."
msgstr "30秒以内にモニタホスト情報の取得に失敗しました。外部プロセスによるPOST `<host>:<port>/interrupt` のリクエストで終了させることができません。"

#: pyfemtet/opt/femopt.py:434
#, python-brace-format
msgid ""
"After the program ends, you can check the optimization results using the result viewer.\n"
"The result viewer can be launched by performing one of the following actions:\n"
"- (Windows only) Launch the `pyfemtet-opt-result-viewer` shortcut on your desktop if exists.\n"
"- (Windows only) Launch {path}.\n"
"- Execute \"py -m pyfemtet.opt.visualization.history_viewer\" in the command line"
msgstr ""

#: pyfemtet/opt/femopt.py:459
msgid "Press Enter to quit..."
msgstr "終了するには Enter キーを押してください..."

#: pyfemtet/opt/femopt.py:466
msgid "All processes are terminated."
msgstr "すべてのプロセスが終了しました。"

#: pyfemtet/opt/history/_history.py:299
#, python-brace-format
msgid "The name `{name}` is duplicated. Please use another name."
msgstr "名前「{name}」が重複しています。別の名前を使用してください。"

#: pyfemtet/opt/history/_history.py:1002
#, python-brace-format
msgid "History csv file ({path}) is in use and cannot be written to. Please free this file before exiting the program, otherwise history data will be lost."
msgstr "履歴 CSV ファイル({path})は使用中のため書き込みできません。プログラム終了前にこのファイルの使用を解除してください。そうしないと履歴データが失われます。"

#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:412
#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:901
#, python-brace-format
msgid "{procedure_kind} procedure {procedure_name} is running..."
msgstr "{procedure_kind} 手順 {procedure_name} を実行中..."

#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:436
#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:854
#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:923
#, python-brace-format
msgid "Failed to run macro {procedure_name}. The original message is: {exception}"
msgstr "マクロ {procedure_name} の実行に失敗しました。元のメッセージ：{exception}"

#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:448
msgid "Launching and connecting to Microsoft Excel..."
msgstr "Microsoft Excel を起動して接続しています..."

#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:456
msgid "The connection to Excel is established."
msgstr "Excel への接続が確立されました。"

#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:510
#, python-brace-format
msgid "Femtet XLA file not found: {xla_file_path}"
msgstr "Femtet XLA ファイルが見つかりません: {xla_file_path}"

#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:756
#, python-brace-format
msgid "{xla_file_path} not found. Please check the \"Enable Macros\" command was executed."
msgstr "{xla_file_path} が見つかりませんでした。 「マクロを有効にする」コマンドが実行されたか確認してください。"

#: pyfemtet/opt/interface/_excel_interface/excel_interface.py:814
msgid "The cell address specification by named range is failed. The process changes the specification method to table based."
msgstr "セルアドレスの指定を名前付き範囲で行うことに失敗しました。処理は指定方法をテーブルベースに変更します。"

#: pyfemtet/opt/interface/_femtet_interface/femtet_interface.py:235
#, python-brace-format
msgid "Closing Femtet (pid = {pid}) ..."
msgstr "Femtet(pid = {pid})を終了しています・・・"

#: pyfemtet/opt/interface/_femtet_interface/femtet_interface.py:239
msgid "Femtet is closed."
msgstr "Femtet は終了しました。"

#: pyfemtet/opt/interface/_femtet_interface/femtet_interface.py:524
#, python-brace-format
msgid "{name} does not finish in {warning_time_sec} seconds. If the optimization is hanging, the most reason is a dialog is opening in Femtet and it waits for your input. Please confirm there is no dialog in Femtet."
msgstr "{name} は {warning_time_sec} 秒以内に終了しませんでした。最適化が停止している場合、主な原因は Femtet 内でダイアログが開いており、入力を待っていることです。Femtet にダイアログが表示されていないことを確認してください。"

#: pyfemtet/opt/interface/_femtet_with_nx_interface/femtet_with_nx_interface.py:40
msgid ""
"`run_journal.exe` is not found. Please check:\n"
"- NX is installed.\n"
"- The environment variable `UGII_BASE_DIR` is set.\n"
"- `<UGII_BASE_DIR>\\NXBIN\\run_journal.exe` exists.\n"
msgstr ""

#: pyfemtet/opt/interface/_femtet_with_solidworks/femtet_with_solidworks_interface.py:93
msgid "Failed to update Solidworks model."
msgstr "Solidworksモデルの更新に失敗しました。"

#: pyfemtet/opt/interface/_solidworks_interface/solidworks_interface.py:67
msgid "Failed to instantiate Solidworks. Please check installation and enabling macro."
msgstr "Solidworks の起動に失敗しました。インストールとマクロの有効化を確認してください。"

#: pyfemtet/opt/interface/_surrogate_model_interface/botorch_interface.py:255
#, python-brace-format
msgid "The surrogate model estimated that the probability of feasibility (PoF) is {pof}. This is under {thresh}. So this trial is processed as a constraint violation."
msgstr "代理モデルは実行可能確率(PoF)が {pof} と推定しました。これは {thresh} 未満です。したがって、この試行は拘束違反として処理されます。"

#: pyfemtet/opt/optimizer/_base_optimizer.py:40
msgid "----- Hidden constraint violation! -----"
msgstr "----- 隠れた拘束違反！ -----"

#: pyfemtet/opt/optimizer/_base_optimizer.py:41
#, python-brace-format
msgid "error: {err_msg}"
msgstr "エラー: {err_msg}"

#: pyfemtet/opt/optimizer/_base_optimizer.py:51
#, python-brace-format
msgid "There are duplicated name {name}. If there are duplicate names for parameters or objective functions, the later defined ones will overwrite the earlier ones. Please be careful to ensure that this overwriting is intentional."
msgstr "名前{name}が重複しています。パラメータや目的関数の名前が重複している場合、後に定義されたものが先のものを上書きします。この上書きが意図的であることを必ずご確認ください。"

#: pyfemtet/opt/optimizer/_base_optimizer.py:136
#, python-brace-format
msgid "Supported variable types are Real or str, got {type}"
msgstr "対応している変数の型はRealまたはstrです。{type}が指定されました。"

#: pyfemtet/opt/optimizer/_base_optimizer.py:275
msgid "`names` must be a string or an array of strings."
msgstr "`names` は文字列または文字列の配列でなければなりません。"

#: pyfemtet/opt/optimizer/_base_optimizer.py:315
msgid "One of `lower_bound` and `upper_bound` should be set."
msgstr "`lower_bound` と `upper_bound` のいずれか一方を設定してください。"

#: pyfemtet/opt/optimizer/_base_optimizer.py:399
msgid "----- Hard constraint violation! -----"
msgstr "----- 拘束違反！ -----"

#: pyfemtet/opt/optimizer/_base_optimizer.py:400
#, python-brace-format
msgid "constraint: {name}"
msgstr "拘束: {name}"

#: pyfemtet/opt/optimizer/_base_optimizer.py:401
#, python-brace-format
msgid "evaluated value: {value}"
msgstr "評価値：{value}"

#: pyfemtet/opt/optimizer/_base_optimizer.py:403
#, python-brace-format
msgid "lower bound: {lb}"
msgstr "下限値：{lb}"

#: pyfemtet/opt/optimizer/_base_optimizer.py:406
#, python-brace-format
msgid "upper bound: {ub}"
msgstr "上限：{ub}"

#: pyfemtet/opt/optimizer/_base_optimizer.py:493
#, python-brace-format
msgid "fidelity: ({name})"
msgstr "忠実度：({name})"

#: pyfemtet/opt/optimizer/_base_optimizer.py:494
msgid "input variables:"
msgstr "入力変数："

#: pyfemtet/opt/optimizer/_base_optimizer.py:498
msgid "updating variables..."
msgstr "変数を更新中..."

#: pyfemtet/opt/optimizer/_base_optimizer.py:503
msgid "evaluating constraint functions..."
msgstr "拘束関数を評価しています..."

#: pyfemtet/opt/optimizer/_base_optimizer.py:514
msgid "Hidden constraint violation during hard constraint function evaluation: "
msgstr "ハード拘束関数評価中の隠れた拘束違反："

#: pyfemtet/opt/optimizer/_base_optimizer.py:528
msgid "Hard constraint violation: "
msgstr "厳格拘束違反:"

#: pyfemtet/opt/optimizer/_base_optimizer.py:534
msgid "Solving FEM..."
msgstr ""

#: pyfemtet/opt/optimizer/_base_optimizer.py:549
msgid "Hidden constraint violation in FEM update: "
msgstr "FEM 更新時の隠れた拘束違反："

#: pyfemtet/opt/optimizer/_base_optimizer.py:555
msgid "evaluating objective functions..."
msgstr "目的関数を評価しています..."

#: pyfemtet/opt/optimizer/_base_optimizer.py:569
msgid "Hidden constraint violation during objective function evaluation: "
msgstr "目的関数評価中の隠れた拘束違反："

#: pyfemtet/opt/optimizer/_base_optimizer.py:576
msgid "evaluating remaining constraints..."
msgstr "残りの拘束を評価中..."

#: pyfemtet/opt/optimizer/_base_optimizer.py:594
msgid "Hidden constraint violation during soft constraint function evaluation: "
msgstr "ソフト拘束関数評価中の隠れた拘束違反："

#: pyfemtet/opt/optimizer/_base_optimizer.py:608
msgid "output:"
msgstr "出力:"

#: pyfemtet/opt/optimizer/_base_optimizer.py:728
#, python-brace-format
msgid "===== Exception raised in worker {worker_idx} ====="
msgstr "===== ワーカー {worker_idx} で例外が発生しました ====="

#: pyfemtet/opt/optimizer/_base_optimizer.py:736
#, python-brace-format
msgid "{name}: {exc_val}"
msgstr "{name}: {exc_val}"

#: pyfemtet/opt/optimizer/_base_optimizer.py:747
#, python-brace-format
msgid "worker `{worker}` started."
msgstr "ワーカー `{worker}` が起動しました。"

#: pyfemtet/opt/optimizer/_base_optimizer.py:784
#, python-brace-format
msgid "worker `{worker}` successfully finished!"
msgstr "ワーカー `{worker}` が正常に完了しました！"

#: pyfemtet/opt/optimizer/scipy_optimizer/_scipy_optimizer.py:60
msgid "`ScipyOptimizer` cannot use timeout."
msgstr "`ScipyOptimizer` はタイムアウトを使用できません。"

#: pyfemtet/opt/optimizer/scipy_optimizer/_scipy_optimizer.py:72
msgid "`ScipyOptimizer` cannot use n_trials."
msgstr "`ScipyOptimizer` は n_trials を使用できません。"

#: pyfemtet/opt/optimizer/scipy_optimizer/_scipy_optimizer.py:86
msgid "Scipy can optimize only numerical parameters."
msgstr "Scipyは数値パラメータのみを最適化できます。"

#: pyfemtet/opt/problem/problem.py:168
#, python-brace-format
msgid "Index {i} is over n_return={n_return}."
msgstr "インデックス {i} が n_return={n_return} を超えています。"

#: pyfemtet/opt/problem/problem.py:195
#, python-brace-format
msgid "The number of return values of {fun_name} is {n_values}. This is inconsistent with the specified n_return; {n_return}."
msgstr "{fun_name} の返り値の数は {n_values} です。指定された返り値の数 {n_return} と一致しません。"

#: pyfemtet/opt/problem/variable_manager/_variable_manager.py:187
#, python-brace-format
msgid "Missing arguments! The arguments specified by `args`: {var_args} / The arguments specified by `kwargs`: {var_kwargs} / Required arguments: {msg}"
msgstr "引数が不足しています！`args` に指定された引数：{var_args} / `kwargs` に指定された引数：{var_kwargs} / 必要な引数：{msg}"

#: pyfemtet/opt/problem/variable_manager/_variable_manager.py:201
msgid "Extra positional argument name cannot be duplicated with a variable name."
msgstr "変数名と重複する余分な位置引数名を指定することはできません。"

#: pyfemtet/opt/problem/variable_manager/_variable_manager.py:218
msgid "Extra keyword argument name cannot be duplicated with a variable name."
msgstr "追加のキーワード引数 name は変数名と重複できません。"

#: pyfemtet/opt/problem/variable_manager/_variable_manager.py:290
#, python-brace-format
msgid "invalid format {format} is passed to VariableManager.get_variables(). Valid formats are one of (`raw`, `dict`, `values`)."
msgstr "VariableManager.get_variables() に渡されたフォーマット {format} が無効です。有効なフォーマットは `raw`、`dict`、`values` のいずれかです。"

#: pyfemtet/opt/visualization/history_viewer/_process_monitor/_pages.py:68
#, python-brace-format
msgid "Keep {y_or_xy} ranges"
msgstr "{y_or_xy} の範囲を維持してください"

#: pyfemtet/opt/visualization/history_viewer/result_viewer/_pages.py:220
#, python-brace-format
msgid ".pdt file ({pdt_path}) is not found. Please check the .Results folder. Note that .pdt file save mode depends on the `save_pdt` argument of FemtetInterface in optimization script(default to `all`)."
msgstr ".pdt ファイル({pdt_path})が見つかりません。.Results フォルダを確認してください。.pdt ファイルの保存モードは最適化スクリプト内の FemtetInterface の `save_pdt` 引数に依存します(デフォルトは `all` です)。"

#: pyfemtet/opt/visualization/history_viewer/result_viewer/_pages.py:295
#, python-brace-format
msgid "Unknown error has occurred in analysis model compatibility check. Exception message: {e}"
msgstr "解析モデル互換性チェックで不明なエラーが発生しました。例外メッセージ：{e}"

#: pyfemtet/opt/visualization/plotter/pm_graph_creator.py:146
msgid "Upper of pred. std-dev"
msgstr "予測の標準偏差(+)"

#: pyfemtet/opt/visualization/plotter/pm_graph_creator.py:150
msgid "Lower of pred. std-dev"
msgstr "予測の標準偏差(-)"

#: pyfemtet/opt/visualization/plotter/pm_graph_creator.py:183
msgid "Std-dev of pred."
msgstr "予測の標準偏差"

#~ msgid "It was detected that the configuration of Femtet python macro constants has not been completed. The configuration was done automatically (python -m win32com.client.makepy FemtetMacro). Please restart the program."
#~ msgstr ""

#~ msgid "Sheet {sh_name} does not exist in the book {wb_name}."
#~ msgstr ""

#~ msgid "Launching and connecting to Solidworks..."
#~ msgstr ""

#~ msgid "Closing {model_name} in Solidworks..."
#~ msgstr ""

#~ msgid "{model_name} is closed."
#~ msgstr ""

#~ msgid ""
#~ "Hard constraint violation! scipy cannot continue optimization. Only `SLSQP` supports optimization with hard constraint optimization problem. If you see this message even if you are using it, please try to following:\n"
#~ "- Use small `eps` by `options` argument.\n"
#~ "- Set `constraint_enhancement`to the value that it larger than the variation of the constraintfunction when input variables within the range of `eps`."
#~ msgstr ""

#~ msgid "worker {worker_idx} started"
#~ msgstr ""

#~ msgid "worker {worker_idx} successfully finished!"
#~ msgstr ""

#~ msgid "Try to connect Femtet."
#~ msgstr ""

#~ msgid "Open result failed."
#~ msgstr ""
